### ISSUE TITLE
Uncaught TypeError: Cannot read property 'price_usd' of undefined

### ISSUE THREAD

**Issue by wbt** [cyril/atom-ethereum-status-bar#1]
While working normally, I am occasionally getting big red popup errors.
Uncaught TypeError: Cannot read property 'price_usd' of undefined

This is at ethereum-price.js:17.

**Proposed solution**: Add an undefined check and handle it better than throwing an error.  If there are more than a few undefined results in a row, change the displayed price to `???` or similar.

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ethereum-status-bar](https://github.com/cyril/atom-ethereum-status-bar) package 0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'price_usd' of undefined

```

TypeError: Cannot read property 'price_usd' of undefined
    at /packages/ethereum-status-bar/lib/ethereum-price.js:17:14)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -4:05.8.0 snippets:next-tab-stop (input.hidden-input)
     -4:05.8.0 snippets:expand (input.hidden-input)
     -4:05.8.0 editor:indent (input.hidden-input)
     -4:05.1.0 core:backspace (input.hidden-input)
     -4:01.6.0 core:paste (input.hidden-input)
 19x -3:55.8.0 core:delete (input.hidden-input)
  2x -3:51.2.0 core:backspace (input.hidden-input)
  6x -3:50.5.0 core:move-down (input.hidden-input)
     -3:48.9.0 core:move-left (input.hidden-input)
     -3:46.2.0 editor:newline (input.hidden-input)
 51x -3:35.9.0 core:backspace (input.hidden-input)
     -1:29.9.0 core:delete (input.hidden-input)
  3x -1:29.3.0 core:move-left (input.hidden-input)
     -1:28 core:delete (input.hidden-input)
     -0:20.3.0 core:save (input.hidden-input)
     -0:17.6.0 tree-view:show-in-file-manager (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
autocomplete-solidity 0.3.4 
bitcoin-status-bar 0.2.0 
ethereum-status-bar 0.1.4 
fold-navigator 0.0.622 
language-ethereum 0.3.9 
markdown-folding 0.3.1 
pretty-json 2.1.2 
simple-drag-drop-text 0.5.0 
tortoise-svn 0.5.1 
```

**Comment by wbt** [comment]
This seems to be happening fairly often now, and can be reliably triggered by going to Packages-> Ethereum Status Bar -> Toggle.

I am disabling the package for now.

**Comment by wbt** [comment]
Core of the issue:
The extension gets price information by making an HTTP call to https://api.coinmarketcap.com/v1/ticker/ethereum/?convert=USD which returns HTTP 410 Gone, with the message "WARNING: This API is now offline. Please switch to the new CoinMarketCap API. (https://pro.coinmarketcap.com/migrate/)"

Making use of the new API would basically require every user of this extension to create a developer account at CoinMarketCap, create an API key, and enter that API key in settings for this extension.  

As users of this extension are highly likely to be developers, this is not necessarily infeasible.  However, it does seem like a pretty good chunk of work compared to the value added; it might be easier to find a different price oracle.

I am uninstalling until the issue is fixed, but no hard feelings if it isn't.  Thanks for what was a useful tool for a while!

**Comment by captainreptile** [comment]
its nice feature for programing while keeping an eye on the market if you are trading

What about using this API instead?
`GET https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=BTC,USD,EUR`

I would try to fix it when i have time, or @cyril could do it pretty fast
@wbt did you fix it? as i see you requested to pull

**Comment by wbt** [comment]
@captainreptile Nope, my PR doesn't fix the main issue.  The repo has an MIT license.  I'd say go for it!

**Comment by cyril** [comment]
Thanks for the report.  Happy to see you like this ticker too!

CryptoCompare looks good, let's use it instead!
